const sampleData = {
  products: [
    {
      name: 'Hand-Knitted Penguin Toy',
      slug: 'hand-knitted-penguin-toy',
      category: 'Toys & Decor',
      images: ['/images/penguin.jpg'],
      brand: 'Devastram Artisan',
      description: 'A beautifully hand-knitted, adorable penguin toy made with love and soft yarn. Perfect as a gift or for home decor.',
      price: 24.99,
      stock: 15,
      rating: 4.8,
      numReviews: 12,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Traditional Green & Gold Rings Set',
      slug: 'traditional-green-gold-rings',
      category: 'Jewelry',
      images: ['/images/rings.jpg'],
      brand: 'Devastram Jewels',
      description: 'Elegant set of traditional rings featuring deep green stones and intricate gold detailing. A beautiful addition to your ethnic wear.',
      price: 19.99,
      stock: 30,
      rating: 4.5,
      numReviews: 24,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Decorative Light Bottle with Florals',
      slug: 'decorative-light-bottle-florals',
      category: 'Home Decor',
      images: ['/images/bottle.jpg'],
      brand: 'Devastram Decor',
      description: 'A stunning glass bottle enclosing warm fairy lights and delicate floral decorations, bringing a magical ambiance to any room.',
      price: 34.99,
      stock: 10,
      rating: 4.9,
      numReviews: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Pearl & Gold Floral Necklace Set',
      slug: 'pearl-gold-floral-necklace-set',
      category: 'Jewelry',
      images: ['/images/necklace.jpg'],
      brand: 'Devastram Jewels',
      description: 'A graceful necklace and matching accessories featuring elegant pearl chains and gold-finish floral centerpieces for festive occasions.',
      price: 45.00,
      stock: 20,
      rating: 4.7,
      numReviews: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Laddu Gopal Saffron Poshak',
      slug: 'laddu-gopal-saffron-poshak',
      category: 'Spiritual',
      images: ['/images/laddu-gopal.jpg'],
      brand: 'Devastram Spiritual',
      description: 'Beautifully crafted saffron dress (poshak) for Laddu Gopal (Lord Krishna), adorned with a vibrant hat, Indian flags, and intricate borders.',
      price: 29.99,
      stock: 50,
      rating: 5.0,
      numReviews: 42,
      isFeatured: true,
      banner: null,
    }
  ],
  users: [
    {
      name: 'Nikhil Pandey',
      email: 'nikhilpandey00999@gmail.com',
      password: '123456',
      role: 'admin'
    },
  ]
};

export default sampleData;
